# Generated by Django 3.1 on 2020-10-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicsLab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalVariable',
            new_name='WeekStatus',
        ),
    ]
