# Generated by Django 3.1 on 2020-10-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PhysicsLab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglistuser',
            options={'ordering': ['order_in_waiting_list']},
        ),
        migrations.RemoveField(
            model_name='globalvariable',
            name='lab_status',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_id',
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waitinglistuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
