# Generated by Django 3.1 on 2020-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicsLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labitem',
            name='change_available_tag',
            field=models.BooleanField(default=False),
        ),
    ]
