# Generated by Django 3.1 on 2020-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicsLab', '0002_auto_20201008_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='week',
        ),
        migrations.AddField(
            model_name='labitem',
            name='lab_week',
            field=models.IntegerField(default=0),
        ),
    ]
